### ISSUE TITLE
English Please

### ISSUE THREAD

**Issue by hobolance** [xiaolai/regular-investing-in-box#72]
### What is the problem with Chinese README's

Firstly, we congratulate you for getting so much star by sharing this repository with humanity.

But it is very disappointing for non-Chinese speakers when one couldn't understand what a trending repository is about.

When we see such a repo on trending, our minds are blurring like Gollum's.

![Gollum Image](https://media.giphy.com/media/V4uGHRgz0zi6Y/giphy-downsized-large.gif)

There is a way **you can help** to solve this disappointment which I believe is experienced by many people who want to know more about your valuable work and appreciate it.

### What we want:
 - Please add English translation of your README so you are sharing your work and knowledge with more people.

### How this will help you:
 - More feedback to fix and improve your project.
 - New ideas about your project.
 - Greater fame.
 - ![SungerBob Image](https://media.giphy.com/media/3o7absbD7PbTFQa0c8/source.gif)

---

_“Sharing knowledge is the most fundamental act of friendship. Because it is a way you can give something without loosing something.”_

_**— Richard Stallman**_

**Thank you!**	

> The developers of repo will not be held responsible for problems that arise in this script.

> This issue generated by [us/english-please](github.com/us/english-please) script. Please open issue on any error. Thank you!

**Comment by windmaomao** [comment]
I kinda agree with the author in a lot of place, however, there's one point that people needs to understand which is the assumption of this book, the price needs to increase eventually, and the price needs to be most of time increasing. Otherwise, this theory would doom to fail. 

Writing at the moment when the US stock is extremely high in the entire human history is another interesting fact. If you look at the Japan stock, you might draw different conclusion due to the fact that ten years might be the limit how a person can lose his patience. 

Therefore it goes back to the same question, how do I know what is the most successful thing to chase? We have to answer couple of questions, ex. how long you would rank the time it takes to lose your patience, and how big the lost it'll crush you (your tolerance). Without understanding these secondary question, we won't answer the first question, which makes it a circle. My personal take, there's no solution to this. 

You just have to build a sense what might be the successful thing, if you fail, you just start all over again. It's very difficult to tell if you actually made any mistake in one particular of your timeline. Only time can tell you, only certain amount of time can tell you. Unfortunately that certain amount is unknown until known.
